"""Update Affiliate discount_pcts

Revision ID: 3549706daeb8
Revises: 4f7d3b41be85
Create Date: 2026-07-20 15:58:09.145786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3549706daeb8'
down_revision: Union[str, None] = '4f7d3b41be85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_app_affiliate_commissions_payment_id'), 'app_affiliate_commissions', ['payment_id'], unique=False)
    op.add_column('app_affiliates', sa.Column('discount_pcts', sa.String(length=20), nullable=True))
    op.alter_column('app_affiliates', 'payment_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('pf', 'pj', name='partnerpaymenttype', native_enum=False, length=40),
               existing_nullable=True)
    op.drop_column('app_affiliates', 'discount_pct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_affiliates', sa.Column('discount_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.alter_column('app_affiliates', 'payment_type',
               existing_type=sa.Enum('pf', 'pj', name='partnerpaymenttype', native_enum=False, length=40),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('app_affiliates', 'discount_pcts')
    op.drop_index(op.f('ix_app_affiliate_commissions_payment_id'), table_name='app_affiliate_commissions')
    # ### end Alembic commands ###
