"""add match deep analysis table

Revision ID: 4f7d3b41be85
Revises: a1b2c3d4e5f6
Create Date: 2026-07-19 07:52:06.197292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7d3b41be85'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_match_deep_analyses',
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('analyst_name', sa.String(length=120), nullable=False),
    sa.Column('markdown_content', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_match_deep_analyses_fixture_id'), 'app_match_deep_analyses', ['fixture_id'], unique=True)
    # ### end Alembic commands ###
    # NOTA: o autogenerate também detectou drift pré-existente e não-relacionado em
    # app_affiliates/app_affiliate_commissions (índice faltando + VARCHAR->Enum) --
    # removido desta migration de propósito, não é o escopo daqui e uma mudança de
    # tipo de coluna merece revisão própria, não ir de carona numa migration aditiva.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_match_deep_analyses_fixture_id'), table_name='app_match_deep_analyses')
    op.drop_table('app_match_deep_analyses')
    # ### end Alembic commands ###
