// Nomes de seleções em PT-BR. A chave (em inglês) continua sendo o identificador
// usado na API e nos índices; isto é só para EXIBIÇÃO. Seleções regionais/obscuras
// sem nome consagrado em PT caem no fallback (nome original).
const PT: Record<string, string> = {
  Afghanistan: 'Afeganistão', Albania: 'Albânia', Algeria: 'Argélia',
  'American Samoa': 'Samoa Americana', Andorra: 'Andorra', Angola: 'Angola',
  Anguilla: 'Anguila', 'Antigua and Barbuda': 'Antígua e Barbuda', Argentina: 'Argentina',
  Armenia: 'Armênia', Aruba: 'Aruba', Australia: 'Austrália', Austria: 'Áustria',
  Azerbaijan: 'Azerbaijão', Bahamas: 'Bahamas', Bahrain: 'Bahrein', Bangladesh: 'Bangladesh',
  Barbados: 'Barbados', Belarus: 'Belarus', Belgium: 'Bélgica', Belize: 'Belize',
  Benin: 'Benin', Bermuda: 'Bermudas', Bhutan: 'Butão', Bolivia: 'Bolívia',
  Bonaire: 'Bonaire', 'Bosnia and Herzegovina': 'Bósnia e Herzegovina', Botswana: 'Botsuana',
  Brazil: 'Brasil', 'British Virgin Islands': 'Ilhas Virgens Britânicas', Brunei: 'Brunei',
  Bulgaria: 'Bulgária', 'Burkina Faso': 'Burquina Faso', Burundi: 'Burundi',
  Cambodia: 'Camboja', Cameroon: 'Camarões', Canada: 'Canadá', 'Cape Verde': 'Cabo Verde',
  'Cayman Islands': 'Ilhas Cayman', 'Central African Republic': 'República Centro-Africana',
  Chad: 'Chade', Chile: 'Chile', China: 'China', Colombia: 'Colômbia', Comoros: 'Comores',
  Congo: 'Congo', 'Cook Islands': 'Ilhas Cook', 'Costa Rica': 'Costa Rica', Croatia: 'Croácia',
  Cuba: 'Cuba', 'Curaçao': 'Curaçao', Cyprus: 'Chipre', 'Czech Republic': 'República Tcheca',
  'DR Congo': 'RD Congo', Denmark: 'Dinamarca', Djibouti: 'Djibuti', Dominica: 'Dominica',
  'Dominican Republic': 'República Dominicana', Ecuador: 'Equador', Egypt: 'Egito',
  'El Salvador': 'El Salvador', England: 'Inglaterra', 'Equatorial Guinea': 'Guiné Equatorial',
  Eritrea: 'Eritreia', Estonia: 'Estônia', Eswatini: 'Essuatíni', Ethiopia: 'Etiópia',
  'Falkland Islands': 'Ilhas Malvinas', 'Faroe Islands': 'Ilhas Faroé', Fiji: 'Fiji',
  Finland: 'Finlândia', France: 'França', 'French Guiana': 'Guiana Francesa', Gabon: 'Gabão',
  Gambia: 'Gâmbia', Georgia: 'Geórgia', Germany: 'Alemanha', Ghana: 'Gana', Gibraltar: 'Gibraltar',
  Greece: 'Grécia', Greenland: 'Groenlândia', Grenada: 'Granada', Guadeloupe: 'Guadalupe',
  Guam: 'Guam', Guatemala: 'Guatemala', Guernsey: 'Guernsey', Guinea: 'Guiné',
  'Guinea-Bissau': 'Guiné-Bissau', Guyana: 'Guiana', Haiti: 'Haiti', Honduras: 'Honduras',
  'Hong Kong': 'Hong Kong', Hungary: 'Hungria', Iceland: 'Islândia', India: 'Índia',
  Indonesia: 'Indonésia', Iran: 'Irã', Iraq: 'Iraque', 'Isle of Man': 'Ilha de Man',
  Israel: 'Israel', Italy: 'Itália', 'Ivory Coast': 'Costa do Marfim', Jamaica: 'Jamaica',
  Japan: 'Japão', Jersey: 'Jersey', Jordan: 'Jordânia', Kazakhstan: 'Cazaquistão',
  Kenya: 'Quênia', Kosovo: 'Kosovo', Kuwait: 'Kuwait', Kyrgyzstan: 'Quirguistão',
  Laos: 'Laos', Latvia: 'Letônia', Lebanon: 'Líbano', Lesotho: 'Lesoto', Liberia: 'Libéria',
  Libya: 'Líbia', Liechtenstein: 'Liechtenstein', Lithuania: 'Lituânia', Luxembourg: 'Luxemburgo',
  Macau: 'Macau', Madagascar: 'Madagascar', Malawi: 'Malawi', Malaysia: 'Malásia',
  Maldives: 'Maldivas', Mali: 'Mali', Malta: 'Malta', 'Marshall Islands': 'Ilhas Marshall',
  Martinique: 'Martinica', Mauritania: 'Mauritânia', Mauritius: 'Maurício', Mayotte: 'Mayotte',
  Mexico: 'México', Moldova: 'Moldávia', Monaco: 'Mônaco', Mongolia: 'Mongólia',
  Montenegro: 'Montenegro', Montserrat: 'Montserrat', Morocco: 'Marrocos', Mozambique: 'Moçambique',
  Myanmar: 'Mianmar', Namibia: 'Namíbia', Nepal: 'Nepal', Netherlands: 'Países Baixos',
  'New Caledonia': 'Nova Caledônia', 'New Zealand': 'Nova Zelândia', Nicaragua: 'Nicarágua',
  Niger: 'Níger', Nigeria: 'Nigéria', 'North Korea': 'Coreia do Norte',
  'North Macedonia': 'Macedônia do Norte', 'Northern Ireland': 'Irlanda do Norte',
  Norway: 'Noruega', Oman: 'Omã', Pakistan: 'Paquistão', Palestine: 'Palestina',
  Panama: 'Panamá', 'Papua New Guinea': 'Papua-Nova Guiné', Paraguay: 'Paraguai', Peru: 'Peru',
  Philippines: 'Filipinas', Poland: 'Polônia', Portugal: 'Portugal', 'Puerto Rico': 'Porto Rico',
  Qatar: 'Catar', 'Republic of Ireland': 'Irlanda', Romania: 'Romênia', Russia: 'Rússia',
  Rwanda: 'Ruanda', 'Réunion': 'Reunião', 'Saint Kitts and Nevis': 'São Cristóvão e Névis',
  'Saint Lucia': 'Santa Lúcia', 'Saint Vincent and the Grenadines': 'São Vicente e Granadinas',
  Samoa: 'Samoa', 'San Marino': 'San Marino', 'Saudi Arabia': 'Arábia Saudita', Scotland: 'Escócia',
  Senegal: 'Senegal', Serbia: 'Sérvia', Seychelles: 'Seicheles', 'Sierra Leone': 'Serra Leoa',
  Singapore: 'Singapura', 'Sint Maarten': 'São Martinho', Slovakia: 'Eslováquia',
  Slovenia: 'Eslovênia', 'Solomon Islands': 'Ilhas Salomão', Somalia: 'Somália',
  'South Africa': 'África do Sul', 'South Korea': 'Coreia do Sul', 'South Sudan': 'Sudão do Sul',
  Spain: 'Espanha', 'Sri Lanka': 'Sri Lanka', Sudan: 'Sudão', Suriname: 'Suriname',
  Sweden: 'Suécia', Switzerland: 'Suíça', Syria: 'Síria', 'São Tomé and Príncipe': 'São Tomé e Príncipe',
  Tahiti: 'Taiti', Taiwan: 'Taiwan', Tajikistan: 'Tajiquistão', Tanzania: 'Tanzânia',
  Thailand: 'Tailândia', 'Timor-Leste': 'Timor-Leste', Togo: 'Togo', Tonga: 'Tonga',
  'Trinidad and Tobago': 'Trinidad e Tobago', Tunisia: 'Tunísia', Turkey: 'Turquia',
  Turkmenistan: 'Turcomenistão', 'Turks and Caicos Islands': 'Ilhas Turcas e Caicos',
  Tuvalu: 'Tuvalu', Uganda: 'Uganda', Ukraine: 'Ucrânia', 'United Arab Emirates': 'Emirados Árabes Unidos',
  'United States': 'Estados Unidos', Uruguay: 'Uruguai', Uzbekistan: 'Uzbequistão',
  Vanuatu: 'Vanuatu', 'Vatican City': 'Vaticano', Venezuela: 'Venezuela', Vietnam: 'Vietnã',
  Wales: 'País de Gales', Yemen: 'Iêmen', Zambia: 'Zâmbia', Zimbabwe: 'Zimbábue',
  'Åland Islands': 'Ilhas Åland', 'Cape Verde Islands': 'Cabo Verde',
};

export function teamPt(name: string): string {
  if (!name) return name;
  return PT[name] ?? name;
}
